trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON_VERSION: '3.11'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'

- script: | 
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: Install Dependencies

- script: | 
    pytest
  displayName: Run Tests

- script: | 
    mkdir output
    cp app.py output/
  displayName: Prepare Artifact

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: output
    artifactName: build-output
  displayName: Publish Build Artifact
